### ISSUE TITLE
Can not run HardwareInit demo on Linux

### ISSUE THREAD

**Issue by 0xdeit** [CesarChodun/SFE-Engine#9]
**Describe the bug**
LWJGL error when trying to run HardwareInit demo.

**To Reproduce**
1. Clone repo
2. Install jdk and ant
3. Run `ant build-all` in repo [readme](https://github.com/CesarChodun/SFE-Engine#engine-installation)
4. Go to `repo/build/demos'
5. Run `java -jar demoname.jar` [readme](https://github.com/CesarChodun/SFE-Engine#running-the-demos)

**Expected behavior**
Demo to output information about Validation Layers and available Vulkan extensions. As said in [Readme - Troubleshooting](https://github.com/CesarChodun/SFE-Engine#troubleshooting)

**Screenshots**
As the demo should be a command line tool, output instead of screenshot:
```
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "pool-1-thread-1" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.system.Library.loadSystem(Library.java:62)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at com.sfengine.core.Application.createAppInfo(Application.java:178)
	at com.sfengine.core.Application.lambda$init$0(Application.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Desktop:**
 - OS: Fedora 32

**Additional context**
Did not have any java-related tools in my system. Installed OpenJDK ver. 1.8.0, Vulkan and Apache Ant with the default package manager `dnf`. Copied glslangValidator bin from sdk dir `1.2.135.0/x86_64/bin`

**Comment by 0xdeit** [comment]
Output of `ant build-all`:
```
(master)$: ant build-all
Buildfile: /home/user/git/SFE-Engine/build.xml
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

download-ivy:
      [get] Getting: https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar
      [get] To: /home/user/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:resolve] :: Apache Ivy 2.4.0 - 20141213170938 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /home/user/git/SFE-Engine/ivysettings.xml
[ivy:resolve] :: resolving dependencies :: #;working@ceres.saturn.local
[ivy:resolve] 	confs: [binaries]
[ivy:resolve] 	found org.jetbrains#annotations;13.0 in main
[ivy:resolve] 	found org.json#json;20190722 in main
[ivy:resolve] 	found org.lwjgl#lwjgl;3.2.3 in main
[ivy:resolve] 	found org.lwjgl#lwjgl-assimp;3.2.3 in main
[ivy:resolve] 	found org.lwjgl#lwjgl-glfw;3.2.3 in main
[ivy:resolve] 	found org.lwjgl#lwjgl-openal;3.2.3 in main
[ivy:resolve] 	found org.lwjgl#lwjgl-stb;3.2.3 in main
[ivy:resolve] 	found org.lwjgl#lwjgl-vma;3.2.3 in main
[ivy:resolve] 	found org.lwjgl#lwjgl-vulkan;3.2.3 in main
[ivy:resolve] 	found org.joml#joml;1.9.20 in main
[ivy:resolve] 	found com.google.gwt#gwt-user;2.5.0 in main
[ivy:resolve] 	found junit#junit;4.12 in main
[ivy:resolve] 	found org.hamcrest#hamcrest-core;1.3 in main
[ivy:resolve] :: resolution report :: resolve 388ms :: artifacts dl 18ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|     binaries     |   13  |   0   |   0   |   0   ||   27  |   0   |
	---------------------------------------------------------------------

get-dependencies:
[ivy:retrieve] :: retrieving :: #
[ivy:retrieve] 	confs: [binaries]
[ivy:retrieve] 	0 artifacts copied, 27 already retrieved (0kB/5ms)

build:

compile:
    [javac] /home/user/git/SFE-Engine/build.xml:139: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 155 source files to /home/user/git/SFE-Engine/build/classes
    [javac] /home/user/git/SFE-Engine/src/main/java/com/sfengine/core/rendering/Presenter.java:18: warning: NotImplementedException is internal proprietary API and may be removed in a future release
    [javac] import sun.reflect.generics.reflectiveObjects.NotImplementedException;
    [javac]                                              ^
    [javac] /home/user/git/SFE-Engine/src/main/java/com/sfengine/core/rendering/Presenter.java:110: warning: NotImplementedException is internal proprietary API and may be removed in a future release
    [javac]                     throw new NotImplementedException();
    [javac]                               ^
    [javac] Note: /home/user/git/SFE-Engine/src/main/java/com/sfengine/core/properties/PropertyDictionary.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 warnings

build-all:
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

download-ivy:

init-ivy:

resolve:

get-dependencies:

build:

compile:

make-demos:
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

make-demo-jar:

make-demo-jar:
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

make-demo-jar:
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

make-demo-jar:

make-demo-jar:

make-demo-jar:

make-demo-jar:
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HelloWindow.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HelloResources.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HardwareInit.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HelloCube.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HelloDescriptor.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HelloTriangle.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/demos/HelloWorld.jar
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

download-ivy:

init-ivy:

get-dependencies:

build:

make-eclipse-jar:
      [jar] Building jar: /home/user/git/SFE-Engine/build/eclipse/lib/dependencies-javadoc.jar
      [jar] Building jar: /home/user/git/SFE-Engine/build/eclipse/lib/dependencies.jar
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

download-ivy:

init-ivy:

resolve:

get-dependencies:

build:

compile:

create-engine-jar:
      [jar] Building jar: /home/user/git/SFE-Engine/build/app/SFEngine.jar
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

download-ivy:

init-ivy:

resolve:

get-dependencies:

build:

compile:

create-engine-source-jar:
      [jar] Building jar: /home/user/git/SFE-Engine/build/app/SFEngine-source.jar
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

download-ivy:

init-ivy:

resolve:

get-dependencies:

build:

compile:

create-engine-javadoc:
  [javadoc] Generating Javadoc
  [javadoc] Javadoc execution
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.device...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.framebufferfactory...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.physicaldevice...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.queue...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.queuefamily...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.renderjob...
  [javadoc] Loading source files for package main.java.com.sfengine.components.contexts.swapchain...
  [javadoc] Loading source files for package main.java.com.sfengine.components.engines...
  [javadoc] Loading source files for package main.java.com.sfengine.components.geometry...
  [javadoc] Loading source files for package main.java.com.sfengine.components.geometry.indexed...
  [javadoc] Loading source files for package main.java.com.sfengine.components.geometry.unindexed...
  [javadoc] Loading source files for package main.java.com.sfengine.components.memory...
  [javadoc] Loading source files for package main.java.com.sfengine.components.rendering...
  [javadoc] Loading source files for package main.java.com.sfengine.components.rendering.pipeline...
  [javadoc] Loading source files for package main.java.com.sfengine.components.resources...
  [javadoc] Loading source files for package main.java.com.sfengine.components.resources.converters...
  [javadoc] Loading source files for package main.java.com.sfengine.components.shaders...
  [javadoc] Loading source files for package main.java.com.sfengine.components.shaders.descriptor_sets...
  [javadoc] Loading source files for package main.java.com.sfengine.components.shaders.descriptors...
  [javadoc] Loading source files for package main.java.com.sfengine.components.transform...
  [javadoc] Loading source files for package main.java.com.sfengine.components.util...
  [javadoc] Loading source files for package main.java.com.sfengine.components.window...
  [javadoc] Loading source files for package main.java.com.sfengine.components.window.input...
  [javadoc] Loading source files for package main.java.com.sfengine.core...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.device...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.framebufferfactory...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.physicaldevice...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.queue...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.queuefamily...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.renderjob...
  [javadoc] Loading source files for package main.java.com.sfengine.core.context.swapchain...
  [javadoc] Loading source files for package main.java.com.sfengine.core.engine...
  [javadoc] Loading source files for package main.java.com.sfengine.core.hardware...
  [javadoc] Loading source files for package main.java.com.sfengine.core.properties...
  [javadoc] Loading source files for package main.java.com.sfengine.core.rendering...
  [javadoc] Loading source files for package main.java.com.sfengine.core.rendering.frames...
  [javadoc] Loading source files for package main.java.com.sfengine.core.rendering.recording...
  [javadoc] Loading source files for package main.java.com.sfengine.core.resources...
  [javadoc] Loading source files for package main.java.com.sfengine.core.result...
  [javadoc] Loading source files for package main.java.com.sfengine.core.synchronization...
  [javadoc] Loading source files for package main.java.com.sfengine.core.synchronization.VkFence...
  [javadoc] Loading source files for package main.java.com.sfengine.core.synchronization.VkSemaphore...
  [javadoc] Loading source files for package test.java.demos.hardwareinit...
  [javadoc] Loading source files for package test.java.demos.helloCube...
  [javadoc] Loading source files for package test.java.demos.helloCube.rendering...
  [javadoc] Loading source files for package test.java.demos.helloDescriptor...
  [javadoc] Loading source files for package test.java.demos.helloDescriptor.rendering...
  [javadoc] Loading source files for package test.java.demos.helloDescriptor.rendering.environment...
  [javadoc] Loading source files for package test.java.demos.helloResources...
  [javadoc] Loading source files for package test.java.demos.helloTriangle...
  [javadoc] Loading source files for package test.java.demos.hellowindow...
  [javadoc] Loading source files for package test.java.demos.helloworld...
  [javadoc] Constructing Javadoc information...
  [javadoc] 1 error
  [javadoc] 54 warnings
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.device
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.framebufferfactory
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.physicaldevice
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.queue
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.queuefamily
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.renderjob
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.contexts.swapchain
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.engines
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.geometry
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.geometry.indexed
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.geometry.unindexed
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.memory
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.rendering
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.rendering.pipeline
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.resources
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.resources.converters
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.shaders
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.shaders.descriptor_sets
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.shaders.descriptors
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.transform
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.util
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.window
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.components.window.input
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.device
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.framebufferfactory
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.physicaldevice
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.queue
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.queuefamily
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.renderjob
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.context.swapchain
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.engine
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.hardware
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.properties
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.rendering
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.rendering.frames
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.rendering.recording
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.resources
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.result
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.synchronization
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.synchronization.VkFence
  [javadoc] javadoc: warning - No source files for package main.java.com.sfengine.core.synchronization.VkSemaphore
  [javadoc] javadoc: warning - No source files for package test.java.demos.hardwareinit
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloCube
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloCube.rendering
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloDescriptor
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloDescriptor.rendering
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloDescriptor.rendering.environment
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloResources
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloTriangle
  [javadoc] javadoc: warning - No source files for package test.java.demos.hellowindow
  [javadoc] javadoc: warning - No source files for package test.java.demos.helloworld
  [javadoc] javadoc: error - No public or protected classes found to document.

BUILD SUCCESSFUL
Total time: 42 seconds
```
